<?php


namespace App\Models;


class ArticlesModel extends Model
{
    public function __construct($connection, $tableName)
    {
        parent::__construct($connection, $tableName);
    }

    function getAll(): array
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }

    function getById($id): array
    {
        return parent::getById($id); // TODO: Change the autogenerated stub
    }

    function delete($id)
    {
        parent::delete($id); // TODO: Change the autogenerated stub
    }

    function addArticle($article)
    {
        $result = $this->db->insert(array(
            'title' => $article['title'],
            'image' => $article['image'],
            'content' => $article['content']
        ))
            ->into($this->table);
    }
    function updateArticle($article){
        $result = $this->db->update($this->table)
            ->where('Id')->is($article['id'])
            ->set(array(
                'title' => $article['title'],
                'image' => $article['image'],
                'content' => $article['content']
            ));
    }
}