<?php


namespace App\Models;


class UsersModel extends Model
{

    public function __construct($conn, $tbName)
    {
        parent::__construct($conn, $tbName);
    }

    function getAll(): array
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }

    function getById($id): array
    {
        return parent::getById($id); // TODO: Change the autogenerated stub
    }

    function delete($id)
    {
        parent::delete($id); // TODO: Change the autogenerated stub
    }
    function addUser($user)
    {
        $result = $this->db->insert(array(
            'login' => $user['login'],
            'password' => $user['password'],
            'avatar' => $user['avatar'],
            'email' => $user['email'],
            'emailVerified' => $user['emailVerified'],
            'rememberToken' => $user['rememberToken'],
            'updateAt' => $user['updateAt'],
            'deletedAt' => $user['deletedAt'],
            'username' => $user['username']
        ))
            ->into($this->table);
    }
    function updateUser($user){
        $result = $this->db->update($this->table)
            ->where('Id')->is($user['id'])
            ->set(array(
                'login' => $user['login'],
                'password' => $user['password'],
                'avatar' => $user['avatar'],
                'email' => $user['email'],
                'emailVerified' => $user['emailVerified'],
                'rememberToken' => $user['rememberToken'],
                'updateAt' => $user['updateAt'],
                'deletedAt' => $user['deletedAt'],
                'username' => $user['username']
            ));
    }
}